export const cx = {
  root: 'btn',
  block: 'btn--block',
  filled: 'btn--filled',
  ghost: 'btn--ghost',
  lg: 'btn--lg',
  md: 'btn--md',
  neutral: 'btn--neutral',
  outline: 'btn--outline',
  primary: 'btn--primary',
  round: 'btn--round',
  secondary: 'btn--secondary',
  sm: 'btn--sm',
  soft: 'btn--soft',
  solid: 'btn--solid',
  xs: 'btn--xs',
  icon: 'btn__icon',
  iconTrailing: 'btn__icon--trailing',
  label: 'btn__label'
} as const
