export const cx = {
  body: 'welcome__body',
  bodyLoader: 'welcome__body-loader',
  divider: 'welcome__divider',
  footer: 'welcome__footer',
  header: 'welcome__header',
  source: 'welcome__source',
  sourceMeta: 'welcome__source-meta',
  sourceName: 'welcome__source-name',
  sourceTier: 'welcome__source-tier',
  sourceTierBase: 'welcome__source-tier--base',
  sourceTierHigh: 'welcome__source-tier--high',
  sourceTierMid: 'welcome__source-tier--mid',
  sources: 'welcome__sources',
  sourcesTitle: 'welcome__sources-title',
  stat: 'welcome__stat',
  statLabel: 'welcome__stat-label',
  statValue: 'welcome__stat-value',
  stats: 'welcome__stats',
  subtitle: 'welcome__subtitle',
  text: 'welcome__text',
  textClosing: 'welcome__text--closing',
  title: 'welcome__title'
} as const
