export const cx = {
  root: 'spirit-view',
  canvas: 'spirit-view__canvas',
  title: 'spirit-view__title',
  subtitle: 'spirit-view__subtitle',
  enterPrompt: 'spirit-view__enter-prompt',
  enterBtn: 'spirit-view__enter-btn',
  breatheRing: 'spirit-view__breathe-ring',
  hud: 'spirit-view__hud',
  hudItem: 'spirit-view__hud-item',
  hudLabel: 'spirit-view__hud-label',
  hudValue: 'spirit-view__hud-value',
  fab: 'spirit-view__fab',
  controlsForm: 'spirit-view__controls-form',
  controlGroup: 'spirit-view__control-group',
  controlLabel: 'spirit-view__control-label',
  controlRow: 'spirit-view__control-row',
  slider: 'spirit-view__slider',
  modeBtn: 'spirit-view__mode-btn',
  modeBtnActive: 'spirit-view__mode-btn--active',
  paletteBtn: 'spirit-view__palette-btn',
  paletteBtnActive: 'spirit-view__palette-btn--active',
  exitBtn: 'spirit-view__exit',
  active: 'spirit-view--active',
  entering: 'spirit-view--entering'
} as const
