import type { Sighting } from '@/types'
import { DataSourceId } from '@/enums'
import { createSourceLoader } from './use-fetch'

// ─── Composable ─────────────────────────────────────────────────────

/**
 * useDowPursue — loader for the U.S. Department of War PURSUE UAP release
 * (war.gov/UFO). Per-year chunks + manifest generated by
 * scripts/process-dow-pursue.mjs. Simple numeric-year manifest keys.
 */
export interface DowPursueSource {
  loadManifest(): Promise<import('./use-fetch').ManifestLike | null>
  loadYearRange(fromYear: number, toYear: number): Promise<Sighting[]>
  loadProgressive(
    fromYear: number,
    toYear: number,
    onChunk: (sightings: Sighting[]) => void,
  ): Promise<Sighting[]>
  getAvailableYears(): number[]
  getTotalCount(): number
  getYearCounts(): Map<number, number>
}

let _instance: DowPursueSource | null = null

export function useDowPursue (): DowPursueSource {
  if (_instance) return _instance

  const loader = createSourceLoader({
    manifestFile: 'dow-pursue-manifest.json',
    defaultSource: DataSourceId.DOW_PURSUE,
    label: 'DoW PURSUE',
    simpleYears: true
  })

  _instance = {
    loadManifest: loader.loadManifest,
    loadYearRange: loader.loadYearRange,
    loadProgressive: loader.loadProgressive,
    getAvailableYears: loader.getAvailableYears,
    getTotalCount: loader.getTotalCount,
    getYearCounts: loader.getYearCounts
  }

  return _instance
}
