export const cx = {
  content: 'modal-sighting__content',
  description: 'modal-sighting__description',
  descriptionSolo: 'modal-sighting__description--solo',
  descriptionWithSummary: 'modal-sighting__description--with-summary',
  footer: 'modal-sighting__footer',
  header: 'modal-sighting__header',
  label: 'modal-sighting__label',
  row: 'modal-sighting__row',
  summary: 'modal-sighting__summary',
  summarySolo: 'modal-sighting__summary--solo',
  summaryWithDesc: 'modal-sighting__summary--with-desc',
  summaryLabel: 'modal-sighting__summary-label',
  title: 'modal-sighting__title',
  value: 'modal-sighting__value',
  sourceLink: 'modal-sighting__source-link',
  relatedSection: 'modal-sighting__related',
  relatedTitle: 'modal-sighting__related-title',
  relatedEmpty: 'modal-sighting__related-empty',
  relatedItem: 'modal-sighting__related-item',
  relatedItemDate: 'modal-sighting__related-item-date',
  relatedItemMeta: 'modal-sighting__related-item-meta',
  relatedItemDistance: 'modal-sighting__related-item-distance',
  relatedItemLink: 'modal-sighting__related-item-link'
} as const
