export const cx = {
  mapCluster: 'map-cluster',
  mapClusterLg: 'map-cluster--lg',
  mapClusterMd: 'map-cluster--md',
  mapClusterSm: 'map-cluster--sm',
  mapClusterXl: 'map-cluster--xl',
  mapClusterWrapper: 'map-cluster-wrapper',
  mapControls: 'sighting-map__controls',
  mapDetails: 'sighting-map__details',
  mapSummary: 'sighting-map__summary',
  mapDetailsContent: 'sighting-map__details-content',
  mapPopup: 'map-popup',
  mapPopupDate: 'map-popup__date',
  mapPopupLocation: 'map-popup__location',
  mapPopupMeta: 'map-popup__meta',
  mapPopupAction: 'map-popup__action',
  mapPopupSummary: 'map-popup__summary',
  sightingMap: 'sighting-map',
  sightingMapOuter: 'sighting-map-outer',
  sightingMapCanvas: 'sighting-map__canvas',
  sightingMapLoader: 'sighting-map__loader'
} as const
